### ISSUE TITLE
database: 提取calypso结构预测结果，构建结构数据库

### ISSUE THREAD

**Issue by ixsluo** [ICCMS-CALYPSO/CALYPSO-kit#3]
### Description & Motivation

构建CALYPSO结构数据库，基于MongoDB数据库。
需要考虑
1. 提取calypso ini opt
2. 明显错误的数据在加入数据库之前就删除（如能量特别低）
3. 先把结构加入数据库，再对已加入数据库的结构进行信息更新
4. 对已加入数据库的结构，再次考虑是否有错误数据（与2的判断条件可能不同）
5. 编写针对晶体结构的数据库查询接口
6. 针对机器学习训练设计筛选方案（不是删除错误数据）

与数据库相关的部分存放于`calypsokit/calydb`目录
与结构分析相关的部分存放于`calypsokit/analysis`目录

**Comment by wangzyphysics** [comment]
已完成第一步：提取calypso ini opt

**Comment by wangzyphysics** [comment]
![image](https://github.com/ICCMS-CALYPSO/CALYPSO-kit/assets/76582286/9c124b10-6fe5-408e-849d-c860efcf2186)
